version: '3'

volumes:
  postgres_data: {}
  postgres_data_backups: {}

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/dev/Dockerfile
    image: fastapi_backend
    container_name: backend
    depends_on:
      - postgres
    volumes:
      - ./src:/app:z
    env_file:
      - ./.envs/.local/.backend
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: backend_postgres
    container_name: backend_postgres
    # command: postgres -c 'max_connections=${POSTGRES_MAX_CONNECTION:-500}'
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - postgres_data_backups:/backups:z
    healthcheck:
      interval: 10s
      retries: 10
      test: 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"'
      timeout: 2s
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '5432:5432'
